<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sherlock.Business\Sherlock.Business.csproj" />
    <ProjectReference Include="..\Sherlock.Data\Sherlock.Data.csproj" />
  </ItemGroup>

</Project>
