// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sherlock.Data.Context;

#nullable disable

namespace Sherlock.Data.Migrations
{
    [DbContext(typeof(SherlockDbContext))]
    [Migration("20251126214154_SeedProviders")]
    partial class SeedProviders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sherlock.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Editor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("editor");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("isbn");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("Isbn")
                        .HasDatabaseName("ix_books_isbn");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_books_title");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.BookPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount");

                    b.Property<int>("LastQueryId")
                        .HasColumnType("integer")
                        .HasColumnName("last_query_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("QueryDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("query_date_time");

                    b.HasKey("Id")
                        .HasName("pk_book_prices");

                    b.HasIndex("BookId", "ProviderId", "QueryDateTime")
                        .HasDatabaseName("ix_book_prices_book_id_provider_id_query_date_time");

                    b.ToTable("book_prices", (string)null);
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BaseShippingCost")
                        .HasColumnType("numeric")
                        .HasColumnName("base_shipping_cost");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MinFreeShipping")
                        .HasColumnType("numeric")
                        .HasColumnName("min_free_shipping");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ProviderCategoryEnum")
                        .HasColumnType("integer")
                        .HasColumnName("provider_category_enum");

                    b.Property<string>("SearchUrlTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_url_template");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_providers");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_providers_url");

                    b.ToTable("providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Alexandre Costa",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaalexandrecosta.com.br/"
                        },
                        new
                        {
                            Id = 2,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Ana Campagnolo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariacampagnolo.com.br/"
                        },
                        new
                        {
                            Id = 3,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Araceli",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadaaraceli.com.br/"
                        },
                        new
                        {
                            Id = 4,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Bene Barbosa",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadobene.com.br/"
                        },
                        new
                        {
                            Id = 5,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Bernardo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadobernardo.com/"
                        },
                        new
                        {
                            Id = 6,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Brodbeck",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariabrodbeck.com.br/"
                        },
                        new
                        {
                            Id = 7,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Bruna Torlay",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariabrunatorlay.com.br/"
                        },
                        new
                        {
                            Id = 8,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Catolikids",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariacatolikids.com.br/"
                        },
                        new
                        {
                            Id = 9,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Cazarre",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariacazarre.com.br/"
                        },
                        new
                        {
                            Id = 10,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Chesterton Brasil",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariachestertonbrasil.com.br/"
                        },
                        new
                        {
                            Id = 11,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Constantino",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadoconsta.com.br/"
                        },
                        new
                        {
                            Id = 12,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Contra os Acadêmicos",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariacontraosacademicos.com.br/"
                        },
                        new
                        {
                            Id = 13,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Daniel Lopez",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livraria.daniellopez.com.br/"
                        },
                        new
                        {
                            Id = 14,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Déia e Tiba",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livraria.deiaetiba.com.br/"
                        },
                        new
                        {
                            Id = 15,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Edmilson Cruz",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaedmilsoncruz.com.br/"
                        },
                        new
                        {
                            Id = 16,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Formação do Imaginário",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://afilivraria.com.br/"
                        },
                        new
                        {
                            Id = 17,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Guilherme Freire",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaguilhermefreire.com.br/"
                        },
                        new
                        {
                            Id = 18,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Rodrigo Gurgel",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livraria.rodrigogurgel.com.br/"
                        },
                        new
                        {
                            Id = 19,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Instituto Borborema",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaib.com/"
                        },
                        new
                        {
                            Id = 20,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Paulo Kogos",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariapaulokogos.com.br/"
                        },
                        new
                        {
                            Id = 21,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Lacombe",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadolacombe.com.br/"
                        },
                        new
                        {
                            Id = 22,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Marcela",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadamarcela.com.br/"
                        },
                        new
                        {
                            Id = 23,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Nikolas",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadonikolas.com/"
                        },
                        new
                        {
                            Id = 24,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Padre Lucas",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadopadrelucas.com.br/"
                        },
                        new
                        {
                            Id = 25,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Pedro Augusto",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariapedroaugusto.com.br/"
                        },
                        new
                        {
                            Id = 26,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Rasta",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadorasta.com.br/"
                        },
                        new
                        {
                            Id = 27,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Roberto Motta",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadorobertomotta.com.br/"
                        },
                        new
                        {
                            Id = 28,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Sabedoria Católica",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariasabedoriacatolica.com.br/"
                        },
                        new
                        {
                            Id = 29,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Thomas",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadothomas.com.br/"
                        },
                        new
                        {
                            Id = 30,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Victor Sales",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariavictorsales.com.br/"
                        },
                        new
                        {
                            Id = 31,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Vista Pátria",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariavistapatria.com.br/"
                        },
                        new
                        {
                            Id = 32,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Luis Enrique",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://www.livrariadoluisenrique.com.br/"
                        },
                        new
                        {
                            Id = 33,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Anália",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://analigialivraria.com.br/"
                        },
                        new
                        {
                            Id = 34,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Silvio Navarro",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadosilvionavarro.com.br/"
                        },
                        new
                        {
                            Id = 35,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Cris Corrêa",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://www.livrariacriscorrea.com.br/"
                        },
                        new
                        {
                            Id = 36,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria PS Zerado",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariapszerado.com.br/"
                        },
                        new
                        {
                            Id = 37,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Vandressa",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadavandressa.com.br/"
                        },
                        new
                        {
                            Id = 38,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Fora da Caixinha",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://www.livrariaforadacaixinha.com.br/"
                        },
                        new
                        {
                            Id = 39,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Bruna Gutstein",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariabrunagutstein.com.br/"
                        },
                        new
                        {
                            Id = 40,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Dantas",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadodantas.com.br/"
                        },
                        new
                        {
                            Id = 41,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Fio Diário",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livraria.fiodiario.com/"
                        },
                        new
                        {
                            Id = 42,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Lara Brenner",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrarialarabrenner.com.br/"
                        },
                        new
                        {
                            Id = 43,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Instituto Liberal",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariainstitutoliberal.com.br/"
                        },
                        new
                        {
                            Id = 44,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria NFC",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrarianfc.com.br/"
                        },
                        new
                        {
                            Id = 45,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Rosaly",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadarosaly.com.br/"
                        },
                        new
                        {
                            Id = 46,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Instituto Mises",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariainstitutomises.com.br/"
                        },
                        new
                        {
                            Id = 47,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Arno",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadoarno.com.br/"
                        },
                        new
                        {
                            Id = 48,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Revista Oeste",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariarevistaoeste.com.br/"
                        },
                        new
                        {
                            Id = 49,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Edison Carlos",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadoedisoncarlos.com.br/"
                        },
                        new
                        {
                            Id = 50,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Diácono",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadodiacono.com.br/"
                        },
                        new
                        {
                            Id = 51,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Rafael Nogueira",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariarafaelnogueira.com.br/"
                        },
                        new
                        {
                            Id = 52,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Liberdade",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadaliberdade.com.br/"
                        },
                        new
                        {
                            Id = 53,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Seu Filho Leitor",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaseufilholeitor.com.br/"
                        },
                        new
                        {
                            Id = 54,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Rebelo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariarebelo.com.br/"
                        },
                        new
                        {
                            Id = 55,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Julia",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadajulia.com.br/"
                        },
                        new
                        {
                            Id = 56,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Camila",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadacamila.com.br/"
                        },
                        new
                        {
                            Id = 57,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Católicos de Verdade",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariacatolicosdeverdade.com.br/"
                        },
                        new
                        {
                            Id = 58,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Lorenzo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadolorenzo.com.br/"
                        },
                        new
                        {
                            Id = 59,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Raphael Tonon",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaraphaeltonon.com.br/"
                        },
                        new
                        {
                            Id = 60,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria BBP",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariabbp.com/"
                        },
                        new
                        {
                            Id = 61,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Laíse",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://www.livrariadalaise.com.br/"
                        },
                        new
                        {
                            Id = 62,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Grimaldo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadogrimaldo.com.br/"
                        },
                        new
                        {
                            Id = 63,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Patthy",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadapatthy.com.br/"
                        },
                        new
                        {
                            Id = 64,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Peregrino",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadoperegrino.com.br/"
                        },
                        new
                        {
                            Id = 65,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Família Católica",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadafamiliacatolica.com.br/"
                        },
                        new
                        {
                            Id = 66,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Grande Família",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariagrandefamilia.com.br/"
                        },
                        new
                        {
                            Id = 67,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Tati",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadatati.com.br/"
                        },
                        new
                        {
                            Id = 68,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Danilo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadodanilo.com.br/"
                        },
                        new
                        {
                            Id = 69,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Santa Carona",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariasantacarona.com.br/"
                        },
                        new
                        {
                            Id = 70,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Marize",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadamarize.com.br/"
                        },
                        new
                        {
                            Id = 71,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Pri Antunes",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariapriantunes.com.br/"
                        },
                        new
                        {
                            Id = 72,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Paula Marisa",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livraria.paulamarisa.com.br/"
                        },
                        new
                        {
                            Id = 73,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Nuzio Neto",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadanuzioneto.com.br/"
                        },
                        new
                        {
                            Id = 74,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Pietra",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadapietra.com.br/"
                        },
                        new
                        {
                            Id = 75,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Doutor Pacheco",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadoutorpacheco.com.br/"
                        },
                        new
                        {
                            Id = 76,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Eduardo Bolsonaro",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaeduardobolsonaro.com.br/"
                        },
                        new
                        {
                            Id = 77,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria CEP",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariacep.com.br/"
                        },
                        new
                        {
                            Id = 78,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Zapparoli",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariazapparoli.com.br/"
                        },
                        new
                        {
                            Id = 79,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Bora Ser Santo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaborasersanto.com.br/"
                        },
                        new
                        {
                            Id = 80,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Cássia",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadacassia.com.br/"
                        },
                        new
                        {
                            Id = 81,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Fran",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadafran.com.br/"
                        },
                        new
                        {
                            Id = 82,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria da Prof",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadaprof.com.br/"
                        },
                        new
                        {
                            Id = 83,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Saulo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadosaulo.com.br/"
                        },
                        new
                        {
                            Id = 84,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Marie Bruno",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://mariebrunobookshop.com.br/"
                        },
                        new
                        {
                            Id = 85,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Rodrigo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadorodrigo.com.br/"
                        },
                        new
                        {
                            Id = 86,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Amanda Buttchevits",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariaamandabuttchevits.com.br/"
                        },
                        new
                        {
                            Id = 87,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Te Atualizei",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariateatualizei.com.br/"
                        },
                        new
                        {
                            Id = 88,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria do Alam",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livrariadoalam.com.br/"
                        },
                        new
                        {
                            Id = 89,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Biblioteca do Luiz",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://bibliotecadoluiz.com.br/"
                        },
                        new
                        {
                            Id = 90,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Livraria Senso Incomum",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://livraria.sensoincomum.org/"
                        },
                        new
                        {
                            Id = 91,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Kirion",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://www.kirion.com.br/"
                        },
                        new
                        {
                            Id = 92,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Vide Editorial",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://videeditorial.com.br/"
                        },
                        new
                        {
                            Id = 93,
                            BaseShippingCost = 15m,
                            IsActive = true,
                            MinFreeShipping = 200m,
                            Name = "Editora Setimo Selo",
                            ProviderCategoryEnum = 100,
                            SearchUrlTemplate = "index.php?route=product/search&search={search}",
                            Url = "https://editorasetimoselo.com.br/"
                        });
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("author");

                    b.Property<int?>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<float?>("Discount")
                        .HasColumnType("real")
                        .HasColumnName("discount");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<bool>("FromCache")
                        .HasColumnType("boolean")
                        .HasColumnName("from_cache");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("product_url");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("QueriedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queried_at");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("response_time_ms");

                    b.Property<string>("SearchIsbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("search_isbn");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_queries_book_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_queries_provider_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_queries_transaction_id");

                    b.HasIndex("TransactionId", "ProviderId")
                        .HasDatabaseName("ix_queries_transaction_id_provider_id");

                    b.HasIndex("SearchIsbn", "ProviderId", "QueriedAt")
                        .HasDatabaseName("ix_queries_search_isbn_provider_id_queried_at")
                        .HasFilter("search_isbn IS NOT NULL");

                    b.ToTable("queries", (string)null);
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.Scraper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ScraperCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("scraper_category_id");

                    b.HasKey("Id")
                        .HasName("pk_scrapers");

                    b.ToTable("scrapers", (string)null);
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("TokenUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_uid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BestQueryId")
                        .HasColumnType("integer")
                        .HasColumnName("best_query_id");

                    b.Property<int>("CostCredits")
                        .HasColumnType("integer")
                        .HasColumnName("cost_credits");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Errors")
                        .HasColumnType("jsonb")
                        .HasColumnName("errors");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_time_ms");

                    b.Property<int>("FailedQueries")
                        .HasColumnType("integer")
                        .HasColumnName("failed_queries");

                    b.Property<string>("InputParameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_parameters");

                    b.Property<int>("ResultTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("result_type_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("SuccessfulQueries")
                        .HasColumnType("integer")
                        .HasColumnName("successful_queries");

                    b.Property<int>("TotalProvidersQueried")
                        .HasColumnType("integer")
                        .HasColumnName("total_providers_queried");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("BestQueryId")
                        .HasDatabaseName("ix_transactions_best_query_id");

                    b.HasIndex("ResultTypeId")
                        .HasDatabaseName("ix_transactions_result_type_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_transactions_started_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_transactions_user_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.TransactionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_billable");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_result_types");

                    b.ToTable("result_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Busca realizada com sucesso",
                            IsBillable = true,
                            IsSuccess = true,
                            Name = "Success"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Busca parcialmente realizada - alguns providers falharam",
                            IsBillable = true,
                            IsSuccess = true,
                            Name = "PartialSuccess"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nenhum resultado encontrado",
                            IsBillable = false,
                            IsSuccess = false,
                            Name = "NoResults"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Todos os providers falharam",
                            IsBillable = false,
                            IsSuccess = false,
                            Name = "AllFailed"
                        });
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("Cpf")
                        .HasColumnType("bigint")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.Query", b =>
                {
                    b.HasOne("Sherlock.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_queries_books_book_id");

                    b.HasOne("Sherlock.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_queries_providers_provider_id");

                    b.HasOne("Sherlock.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Queries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queries_transactions_transaction_id");

                    b.Navigation("Book");

                    b.Navigation("Provider");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Sherlock.Domain.Entities.Query", "BestQuery")
                        .WithMany()
                        .HasForeignKey("BestQueryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_queries_best_query_id");

                    b.HasOne("Sherlock.Domain.Entities.TransactionResult", "TransactionResult")
                        .WithMany()
                        .HasForeignKey("ResultTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_transaction_results_result_type_id");

                    b.HasOne("Sherlock.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_users_user_id");

                    b.Navigation("BestQuery");

                    b.Navigation("TransactionResult");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sherlock.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Queries");
                });
#pragma warning restore 612, 618
        }
    }
}
